APP_TITLE = "Macro Maker (Local Only)"

STATUS_READY = "READY"
STATUS_RECORDING = "RECORDING"
STATUS_PLAYING = "PLAYING"


KILL_SWITCH_TEXT = "Kill switch: press ESC to stop playback"

DEFAULT_REPEAT = 2
DEFAULT_LOOP_SECONDS = 10

MOVE_MIN_INTERVAL = 0.02
MOVE_MIN_DISTANCE = 3
